# Generated by Django 4.2.3 on 2024-07-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_kategori_movie_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
